### ISSUE TITLE
Support for font scaling

### ISSUE THREAD

**Issue by otusweb** [MarceloPrado/flash-calendar#40] opened 2024-06-27 12:22 UTC
The current implementation fails when the user turns on font  scaling

Observed behavior
![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-27 at 14 20 25](https://github.com/MarceloPrado/flash-calendar/assets/1069914/5ef2c4fd-7ebe-4237-9108-7e858ace089e)

expected behavior: the text containers grow vertically to accommodate for taller font. The layout will not be as pretty, but user who want to have a bigger font will be able to view/use the calendar

**Comment by MarceloPrado** [comment] 2024-07-02 11:50
Duplicate of #36

**Closed by MarceloPrado** 2024-07-02 11:50 UTC
